framework:
    secret: '%env(APP_SECRET)%'

    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax

    php_errors:
        log: true

    serializer:
        mapping:
            path:
                - '%kernel.project_dir%/config/api_platform/serialization'
